In [1]:
import numpy as np

In [3]:
print("Это версия: ",np.__version__)
np.show_config()

Это версия:  1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda/envs/PythonCPU\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/Anaconda/envs/PythonCPU\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda/envs/PythonCPU\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\

In [5]:
np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((1, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.array([2.5 for i in range(10)])

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [86]:
vec=np.zeros((1,9))
vec[0][4]=1
vec

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [14]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
np.flip(np.arange(10, 50, 1))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [144]:
np.array(([i for i in range(3)],[i for i in range(3,6)],[i for i in range(6,9)]))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
n=np.array([1,2,0,0,4,0])
for i in np.where(n!=0):
    print(i)

[0 1 4]


In [32]:
np.random.sample((3, 3))

array([[0.06568158, 0.7665321 , 0.92569227],
       [0.60326068, 0.3632613 , 0.08270287],
       [0.17153593, 0.45419081, 0.23402861]])

In [130]:
n=np.random.sample((10,10))
max_=np.zeros((1,10))
min_=np.zeros((1,10))
print(n)
for i in range(10):
    max_[0][i]=(max(n[i]))
    min_[0][i]=(min(n[i]))
print(max(max_[0]))
print(min(min_[0]))


[[0.66820884 0.4681546  0.66429429 0.56353909 0.27456431 0.1478552
  0.43176841 0.70044858 0.47123023 0.44166941]
 [0.46266257 0.54084098 0.90777642 0.70501677 0.07074734 0.06946005
  0.17086198 0.98521255 0.84237681 0.72366888]
 [0.40807001 0.87119701 0.34193933 0.03005837 0.0408794  0.12625334
  0.00740004 0.30927786 0.94211247 0.24399798]
 [0.9056098  0.80070578 0.35370963 0.49762457 0.86672495 0.86759603
  0.02347049 0.82744944 0.23464409 0.00541667]
 [0.61783034 0.25945978 0.2340579  0.77797339 0.51959868 0.54992024
  0.04267243 0.82332223 0.82863889 0.56832109]
 [0.16341529 0.57810242 0.57491494 0.31445647 0.48625929 0.01362978
  0.9327111  0.05784391 0.99512318 0.69047754]
 [0.01328191 0.9870806  0.51297074 0.85653724 0.72987124 0.45511624
  0.61652506 0.11017323 0.1833871  0.90007922]
 [0.04992335 0.40725701 0.45729131 0.47341267 0.15842464 0.67093825
  0.1273545  0.39095746 0.56221465 0.90181791]
 [0.96588197 0.32149741 0.94924412 0.68179486 0.21120928 0.31908795
  0.69856235 

In [93]:
n=np.random.sample((1,10))
print(n)
print(n.mean())

[[0.28042087 0.51986469 0.57657389 0.12219796 0.0863827  0.29756573
  0.78224353 0.92099245 0.95269009 0.03062305]]
0.45695549618787845


In [95]:
n=np.zeros((3,3))
n[0][:]=1
n[2][:]=1
for i in range(3):
    n[i][0]=1
    n[i][2]=1
n

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [65]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


In [115]:
n=np.zeros((5,5))
for i in range(1,5,1):
    n[i][5-i]=i
print(n)
n=np.zeros((5,5))
for i in range(1,5,1):
    n[i][i-1]=i
print(n)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 2. 0.]
 [0. 0. 3. 0. 0.]
 [0. 4. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [138]:
n=np.zeros((5,5))
for i in range(0,5,2):
    for j in range(0,5,2):
        n[i][j]=1
for i in range(1,5,2):
    for j in range(1,5,2):
        n[i][j]=1
n

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [143]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [97]:
np.tile(np.array(([1,0],[0,1])),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])